"use client";

import { ChangeEvent, useMemo, useState } from "react";

type Route = { method: string; path: string; handler_name: string; authenticated: boolean; depth: number; regression_state: string };
type Alert = { code: string; severity: string; route: string; message: string };
type Scan = {
  report: { modified_symbols: { name: string; file?: string; line?: number }[]; max_depth: number; checkpoint: { intent?: string }; impacted_routes: Route[]; alerts: Alert[]; test_selection: { existing_tests: { name: string }[]; stubs: string[] }; local_risk_score: number };
  intelligence: { risk_score: number; classifications: string[]; recommendations: string[]; source: string };
};

const fixture: Scan = {
  report: {
    modified_symbols: [{ name: "sanitizeToken", file: "auth.go", line: 10 }], max_depth: 3,
    checkpoint: { intent: "internal profile refactor only" },
    impacted_routes: [
      { method: "GET", path: "/api/v1/profile", handler_name: "profileHandler", authenticated: true, depth: 2, regression_state: "existing test selected" },
      { method: "POST", path: "/api/v1/webhook", handler_name: "webhookHandler", authenticated: false, depth: 2, regression_state: "coverage stub required" },
    ],
    alerts: [
      { code: "SG-UNAUTH-ROUTE", severity: "high", route: "POST /api/v1/webhook", message: "Unauthenticated endpoint is in the structural blast radius." },
      { code: "SG-INTENT-SCOPE", severity: "high", route: "POST /api/v1/webhook", message: "Checkpoint claims an internal-only change, but a public handler is impacted." },
    ],
    test_selection: { existing_tests: [{ name: "TestProfileHandler" }], stubs: ["TestwebhookHandler_POST_Regression: assert authorization and input validation."] }, local_risk_score: 8,
  },
  intelligence: { risk_score: 8, classifications: ["Structural blast radius", "Unauthenticated route exposure", "BOLA / IDOR review"], recommendations: ["Run selected regression tests", "Assert object-level authorization and request validation"], source: "local-rules" },
};

const panel = "rounded-2xl border border-slate-800/90 bg-slate-950/65 shadow-2xl shadow-black/20 backdrop-blur";

export default function Home() {
  const [scan, setScan] = useState<Scan>(fixture);
  const [isRunning, setIsRunning] = useState(false);
  const [notice, setNotice] = useState("Showing the included security-review fixture.");
  const [selected, setSelected] = useState("sanitizeToken");
  const routes = scan.report.impacted_routes ?? [];
  const tests = scan.report.test_selection?.existing_tests ?? [];
  const risk = scan.intelligence?.risk_score ?? scan.report.local_risk_score;
  const root = scan.report.modified_symbols[0]?.name ?? "selected symbol";
  const graphNodes = useMemo(() => [root, "processAuth", ...routes.map((route) => route.handler_name), ...tests.map((test) => test.name)], [root, routes, tests]);

  function runDemo() { setIsRunning(true); window.setTimeout(() => { setIsRunning(false); setNotice(`Demo complete: ${routes.length} public surface${routes.length === 1 ? "" : "s"} require review.`); }, 650); }
  function importScan(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return;
    const reader = new FileReader();
    reader.onload = () => { try { const raw = JSON.parse(String(reader.result)); const imported = raw.report ? raw : { report: raw, intelligence: { risk_score: raw.local_risk_score, classifications: [], recommendations: [], source: "local-rules" } }; setScan(imported); setSelected(imported.report.modified_symbols?.[0]?.name ?? "selected symbol"); setNotice(`Imported ${file.name}. The evidence below is from that scan.`); } catch { setNotice("That file is not a valid SentryGraph scan report."); } };
    reader.readAsText(file);
  }

  return <main className="min-h-screen overflow-hidden"><div className="mx-auto max-w-7xl px-5 pb-12 pt-5 sm:px-8">
    <header className="flex items-center justify-between border-b border-slate-800/80 pb-5"><div className="flex items-center gap-3"><Mark /><div><p className="font-semibold tracking-tight text-white">SentryGraph</p><p className="text-xs text-slate-500">Entire Sentinel · Security intelligence</p></div></div><div className="hidden items-center gap-2 rounded-full border border-emerald-900/80 bg-emerald-950/30 px-3 py-1.5 text-xs font-medium text-emerald-300 sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />Local evidence engine</div></header>

    <section className="grid gap-8 py-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="mb-4 text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Checkpoint-aware security review</p><h1 className="max-w-3xl text-4xl font-semibold leading-[1.04] tracking-tight text-white sm:text-6xl">Prove what a code change can reach.</h1><p className="mt-5 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">SentryGraph follows a changed symbol through the Entire call graph, exposes every affected API route, and compares the structural evidence with the developer’s declared intent.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={runDemo} disabled={isRunning} className="rounded-lg bg-cyan-300 px-4 py-2.5 text-sm font-bold text-slate-950 transition hover:bg-cyan-200 disabled:cursor-wait disabled:opacity-70">{isRunning ? "Tracing graph…" : "Run included demo"}</button><label className="cursor-pointer rounded-lg border border-slate-700 bg-slate-900/70 px-4 py-2.5 text-sm font-semibold text-slate-200 transition hover:border-slate-500 hover:bg-slate-900">Import scan JSON<input className="hidden" type="file" accept="application/json" onChange={importScan} /></label></div><p className="mt-4 text-xs text-slate-500">Import output from <code className="rounded bg-slate-900 px-1.5 py-1 text-slate-300">entire graph sentry-scan --format json</code> to review a real repository scan.</p></div>
      <div className={`${panel} relative overflow-hidden p-6`}><div className="absolute -right-16 -top-20 h-48 w-48 rounded-full bg-cyan-400/10 blur-3xl" /><p className="relative text-xs font-bold uppercase tracking-[.16em] text-slate-500">The evidence chain</p><div className="relative mt-6 space-y-5"><Proof number="01" title="Graph slice" detail="Reverse CALLS traversal finds every reachable public handler." /><Proof number="02" title="Intent check" detail="Checkpoint claims are tested against actual blast radius." /><Proof number="03" title="Review action" detail="Risks, selected tests, and missing coverage become a decision-ready brief." /></div></div>
    </section>

    <section aria-label="Scan status" className="grid gap-3 sm:grid-cols-4"><Metric label="Modified symbol" value={root} detail={scan.report.modified_symbols[0]?.file ? `${scan.report.modified_symbols[0].file}:${scan.report.modified_symbols[0].line}` : "from imported scan"} /><Metric label="Public surfaces" value={String(routes.length)} detail={`Reverse traversal · depth ${scan.report.max_depth}`} tone={routes.length > 0 ? "cyan" : "muted"} /><Metric label="Review alerts" value={String(scan.report.alerts?.length ?? 0)} detail="Evidence-backed invariants" tone={(scan.report.alerts?.length ?? 0) > 0 ? "rose" : "muted"} /><Metric label="Risk score" value={`${risk}/10`} detail={scan.intelligence?.source === "databricks" ? "Databricks enrichment" : "Deterministic local rules"} tone={risk >= 7 ? "rose" : "emerald"} /></section>
    <p role="status" className="mt-5 text-sm text-slate-400"><span className="mr-2 text-cyan-300">●</span>{notice}</p>

    <section className="mt-5 grid gap-5 lg:grid-cols-[1.6fr_.85fr]"><article className={panel}><div className="flex flex-wrap items-start justify-between gap-3 border-b border-slate-800 p-5"><div><p className="text-sm font-semibold text-white">Structural blast radius</p><p className="mt-1 text-xs text-slate-500">Click a node to inspect the route path from the changed symbol.</p></div><span className="rounded-full border border-slate-700 bg-slate-900 px-2.5 py-1 text-xs font-medium text-slate-300">ENTIRE GRAPH</span></div><Graph nodes={graphNodes} routes={routes} selected={selected} onSelect={setSelected} /><div className="border-t border-slate-800 px-5 py-4 text-sm text-slate-400"><span className="font-medium text-white">Selected evidence:</span> {selected === root ? "Changed symbol is the root of this review." : `${selected} is reachable from ${root} in this scan.`}</div></article>
      <aside className={`${panel} p-5`}><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Decision brief</p><p className="mt-3 text-xl font-semibold leading-7 text-white">An internal-only claim reaches {routes.length} public surface{routes.length === 1 ? "" : "s"}.</p><div className="mt-5 rounded-xl border border-violet-900/70 bg-violet-950/30 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-violet-300">Declared checkpoint intent</p><p className="mt-2 text-sm leading-6 text-violet-100">“{scan.report.checkpoint?.intent || "No intent was supplied."}”</p></div><div className="mt-5 space-y-3">{routes.map((route) => <RouteRow key={`${route.method}-${route.path}`} route={route} />)}{routes.length === 0 && <p className="text-sm text-slate-500">No exposed HTTP routes were found in this scan.</p>}</div></aside>
    </section>

    <section className="mt-5 grid gap-5 lg:grid-cols-3"><article className={`${panel} p-5`}><SectionTitle label="01" title="Security invariants" description="Findings that require reviewer attention." /><div className="mt-5 space-y-3">{(scan.report.alerts ?? []).map((alert) => <div key={`${alert.code}-${alert.route}`} className="border-l-2 border-rose-400 bg-rose-950/20 px-3 py-2.5"><p className="text-xs font-bold text-rose-300">{alert.code} · {alert.route}</p><p className="mt-1 text-xs leading-5 text-slate-400">{alert.message}</p></div>)}{!scan.report.alerts?.length && <p className="text-sm text-slate-500">No policy mismatch detected.</p>}</div></article><article className={`${panel} p-5`}><SectionTitle label="02" title="Regression obligations" description="Test selection is derived from graph relationships." /><div className="mt-5 space-y-3">{tests.map((test) => <p key={test.name} className="flex gap-2 text-sm text-slate-300"><span className="text-emerald-400">✓</span>{test.name}</p>)}{scan.report.test_selection?.stubs.map((stub) => <p key={stub} className="flex gap-2 text-xs leading-5 text-slate-400"><span className="text-amber-300">△</span>{stub}</p>)}</div></article><article className={`${panel} p-5`}><SectionTitle label="03" title="Semantic enrichment" description="Optional Databricks analysis, safely fallible." /><div className="mt-5 space-y-3">{[...(scan.intelligence?.classifications ?? []), ...(scan.intelligence?.recommendations ?? [])].map((item) => <p key={item} className="flex gap-2 text-sm text-slate-300"><span className="text-cyan-300">→</span>{item}</p>)}{!(scan.intelligence?.classifications?.length || scan.intelligence?.recommendations?.length) && <p className="text-sm text-slate-500">Local rules remain the evidence source.</p>}</div></article></section>
    <footer className="mt-9 flex flex-col justify-between gap-2 border-t border-slate-800 pt-5 text-xs text-slate-500 sm:flex-row"><p>SentryGraph · Built with Entire Graph Intelligence</p><p>Structural evidence first. External intelligence is opt-in.</p></footer>
  </div></main>;
}

function Mark() { return <div className="grid h-10 w-10 place-items-center rounded-xl bg-gradient-to-br from-cyan-200 via-cyan-400 to-blue-500 text-lg font-black text-slate-950 shadow-lg shadow-cyan-950/60">S</div>; }
function Proof({ number, title, detail }: { number: string; title: string; detail: string }) { return <div className="flex gap-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-cyan-800 bg-cyan-950/60 text-[10px] font-bold text-cyan-300">{number}</span><div><p className="text-sm font-semibold text-white">{title}</p><p className="mt-1 text-sm leading-5 text-slate-400">{detail}</p></div></div>; }
function Metric({ label, value, detail, tone = "muted" }: { label: string; value: string; detail: string; tone?: "cyan" | "rose" | "emerald" | "muted" }) { const color = { cyan: "text-cyan-300", rose: "text-rose-300", emerald: "text-emerald-300", muted: "text-white" }[tone]; return <article className={`${panel} px-4 py-4`}><p className="text-xs font-medium text-slate-500">{label}</p><p className={`mt-2 truncate text-xl font-semibold tracking-tight ${color}`}>{value}</p><p className="mt-1 truncate text-xs text-slate-500">{detail}</p></article>; }
function SectionTitle({ label, title, description }: { label: string; title: string; description: string }) { return <div><p className="text-xs font-bold tracking-[.16em] text-cyan-300">{label}</p><h2 className="mt-2 font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-slate-500">{description}</p></div>; }
function RouteRow({ route }: { route: Route }) { return <div className="border-t border-slate-800 pt-3"><div className="flex items-center justify-between gap-2"><p className="font-mono text-xs text-slate-200"><span className="mr-2 font-bold text-cyan-300">{route.method}</span>{route.path}</p><span className={`text-[11px] font-medium ${route.authenticated ? "text-emerald-300" : "text-amber-300"}`}>{route.authenticated ? "authenticated" : "review auth"}</span></div><p className="mt-1 text-xs text-slate-500">{route.handler_name} · {route.regression_state}</p></div>; }
function Graph({ nodes, routes, selected, onSelect }: { nodes: string[]; routes: Route[]; selected: string; onSelect: (name: string) => void }) { const positions = [{ x: 38, y: 152 }, { x: 238, y: 152 }, { x: 450, y: 52 }, { x: 450, y: 190 }, { x: 450, y: 328 }]; return <div className="overflow-x-auto bg-[linear-gradient(rgba(30,41,59,.55)_1px,transparent_1px),linear-gradient(90deg,rgba(30,41,59,.55)_1px,transparent_1px)] bg-[size:30px_30px]"><svg className="h-[400px] min-w-[670px] w-full" viewBox="0 0 670 400" role="img" aria-label="SentryGraph call graph">{nodes.slice(1).map((_, index) => { const destination = positions[index + 1] ?? positions[4]; const risky = index > 0 && !routes[index - 1]?.authenticated; return <line key={index} x1={index === 0 ? 188 : 390} y1="181" x2={destination.x} y2={destination.y + 28} stroke={risky ? "#fb7185" : "#38bdf8"} strokeDasharray={risky ? "6 5" : undefined} strokeWidth="2" opacity=".85" />; })}{nodes.map((node, index) => { const position = positions[index] ?? positions[4]; const risky = index > 1 && !routes[index - 2]?.authenticated; const active = selected === node; return <g key={`${node}-${index}`} className="cursor-pointer" onClick={() => onSelect(node)}><rect x={position.x} y={position.y} width="152" height="57" rx="10" fill={active ? "#164e63" : risky ? "#421d2a" : index > 2 ? "#12352d" : "#102a43"} stroke={active ? "#67e8f9" : risky ? "#fb7185" : "#2c5778"} strokeWidth="1.2" /><text x={position.x + 12} y={position.y + 24} fill="white" fontSize="12" fontWeight="700">{node.slice(0, 20)}</text><text x={position.x + 12} y={position.y + 42} fill="#94a3b8" fontSize="10">{index === 0 ? "changed symbol" : index === 1 ? "call chain" : risky ? "security review" : index > 2 ? "selected test" : "HTTP handler"}</text>{risky && <text x={position.x + 112} y={position.y + 23} fill="#fda4af" fontSize="9" fontWeight="700">RISK</text>}</g>; })}</svg></div>; }
